### ISSUE TITLE
Submission: link-preview

### ISSUE THREAD

**Issue by rg-wood** [davatron5000/awesome-standalones#28]
### Name

link-preview

### Category

extensions

### Repo

https://github.com/rg-wood/link-preview

### URL

https://github.com/rg-wood/link-preview

### Install script

npm i @grislyeye/link-preview

### Snippet example

```html
<link-preview>
  <a href="#fragment">Link</a>
</link-preview>
```

**Comment by daviddarnes** [comment]
Here's your submission in the desired JSON format:

```json
{
  "name": "link-preview",
  "category": "extensions",
  "repo": "https://github.com/rg-wood/link-preview",
  "script": "npm i @grislyeye/link-preview",
  "snippet": "<link-preview><a href='#fragment'>Link</a></link-preview>"
}

**Comment by rg-wood** [comment]
Thank you.
