### ISSUE TITLE
Submission: typesense-minibar

### ISSUE THREAD

**Issue by Krinkle** [davatron5000/awesome-standalones#32]
This is a 2kb standalone web component that provides accessible and progressively-enhancing search suggestions. It is in use on https://jquery.com and https://qunitjs.com. It can often replace the popular >100KB Algolia/DocSearch.js widget.

### Name

typesense-minibar

### Category

forms

### Repo

https://github.com/jquery/typesense-minibar

### URL

https://jquery.github.io/typesense-minibar/demo/

### Snippet example

```html
<typesense-minibar><form role="search" action="https://duckduckgo.com"><input type="search" name="q" placeholder="Search..."><input type="hidden" name="sites" value="example.org"></form></typesense-minibar>
```

**Comment by daviddarnes** [comment]
#
Here's your submission in the desired JSON format:

```json
{
  "name": "typesense-minibar",
  "category": "forms",
  "repo": "https://github.com/jquery/typesense-minibar",
  "url": "https://jquery.github.io/typesense-minibar/demo/",
  "snippet": "<typesense-minibar><form role="search" action="https://duckduckgo.com"><input type="search" name="q" placeholder="Search..."><input type="hidden" name="sites" value="example.org"></form></typesense-minibar>"
}
